name: zylo_pages
description: A secure native chat application.
publish_to: 'none'
version: 1.6.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  firebase_database: ^10.5.0
  firebase_storage: ^11.5.6
  # Services
  onesignal_flutter: ^5.0.4
  zego_uikit_prebuilt_call: ^2.14.2
  # State Management & Utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  # UI styling
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0

flutter:
  uses-material-design: true